group 'br.com.oitiliveness3d.oiti_liveness3d'
version '3.5.2'

buildscript {
    ext.kotlin_version = '2.1.21'
    repositories {
        google()
        mavenCentral()

    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.9.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://raw.githubusercontent.com/oititec/android-oiti-versions/master'
        }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'br.com.oitiliveness3d.oiti_liveness3d'
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }

    defaultConfig {
        minSdk = 24
    }

    dependencies {
        implementation("br.com.oiti:liveness3d-sdk:9.5.5")
        implementation("br.com.oiti:security:1.2")
    }
}
