name: Publish to PUB.DEV
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRD
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.7"
      - name: Install Dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run Tests
        run: flutter test
      - name: Format Code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true
